---
- name: Launch ec2 instance
  hosts: localhost
  become: true
  vars_files: 
    - /home/ansible/AWS-Playbooks/keys.yml
  tasks: 
    - name: Create keypair
      ec2_key: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: reyu-key
        state: present
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"  
 
    - name: Launch EC2 instance
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        key_name: reyu-key
        image: ami-0b69ea66ff7391e80
        assign_public_ip: yes
        wait: yes
        count: 1   
        instance_type: t2.micro
        vpc_subnet_id: subnet-0bae8625
        group: ASGSG
        #instance_tags:
        #  app: Kube-master
      register: ec2

    - debug: msg={{ ec2.instances }}

    - name: Gather EC2 instance metadata
      action: ec2_facts
      
    - name: obtain EC2 tags for this instance 
      local_action: 
        module: ec2_tag
        region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
        state: list
      register: ec2_tags

    - name: Set hostname to match EC2 name 
      hostname: name={{ ec2_tags.tags.Name }}
      

    - name: Create SSH Group to login dynamically to EC2 Instance
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webgroup 
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
      loop: "{{ ec2.instances }}"
   
    - name: Wait for SSH to come up 
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"

        
 


