---
- name: Launch ec2 instance
  hosts: localhost
  become: true
  debugger: on_failed
  vars_files: 
    - /home/ansible/AWS-Playbooks/keys.yml
  tasks: 
    - name: Create keypair
      ec2_key: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: pkey
        state: present
      register: ec2keyvar

    - debug: msg={{ ec2keyvar }}

    - name: Save private key
      lineinfile:  
        create: yes
        path: /home/ansible/aws.pem 
        line: "{{ ec2keyvar.key.private_key }}"
        mode: 0600
        owner: ansible
        group: ansible
      when: ec2keyvar.changed

 
    - name: Launch EC2 instance
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        key_name: pkey
       #image: ami-0b69ea66ff7391e80 
        image: ami-0015b9ef68c77328d #CentOS7 community work
        assign_public_ip: yes
        wait: yes
        instance_type: t2.xlarge
        vpc_subnet_id: subnet-0bae8625
        group: ASGSG
      # instance_tags: 
       #  Name: "kubernetes-{{ item }}"
        # environment: dev
#     with_sequence: start=1 end=2
      register: ec2

    - debug: msg={{ ec2.public_ip }}

      
    - name: Tag ec2 instance
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        resource: "{{ item.id }}" 
        state: present
      with_items: "{{ ec2.instances }}"
     #   tags:
      #    Name: "kube-{{ item }}"
       #   env: dev
   #   with_sequence: start=1 end=2
     # with_items: "{{ ec2.instances }}"

 #     add_host:
  #      hostname: "{{ item.public_ip }}"
   #     groupname: webgroup 
    #    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
     #   ansible_ssh_private_key_file: /home/ansible/aws.pem
     # loop: "{{ ec2.instances }}"


    - name: Make entry into all group 
      lineinfile:
        path: /home/ansible/setup-kubernetes-clusternew/inventory/hosts
        insertafter: "[all]"
        line: "{{ item.public_ip }}"
        state: present
      with_items: "{{ ec2.instances }}"


    - name: Add pem key after group all vars
      lineinfile:
        path: /home/ansible/setup-kubernetes-clusternew/inventory/hosts
        insertafter: "[all:vars]"
        line: "ansible_ssh_private_key_file=/home/ansible/aws.pem"
        state: present


    - name: Make entry into inventory perm
      lineinfile:
        path: /home/ansible/setup-kubernetes-clusternew/inventory/hosts 
        insertafter: "[master]"
        line: "{{ item.public_ip }}"
        state: present
      with_items: "{{ ec2.instances }}"

    - name: Make entry into inventory perm
      lineinfile:
        path: /home/ansible/setup-kubernetes-clusternew/inventory/hosts 
        insertafter: "[worker]"
        line: "{{ item.public_ip }}"
        state: present
      with_items: "{{ ec2.instances }}"
     

    - name: Wait for SSH to come up 
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"

